###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: fuzzy-telegram-mysql
      working_dir: /application
      volumes:
        - ..:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=fuzzy-telegram
        - MYSQL_USER=fuzzy-telegram
        - MYSQL_PASSWORD=fuzzy-telegram

    webserver:
      image: nginx:alpine
      container_name: fuzzy-telegram-webserver
      working_dir: /application
      volumes:
          - ..:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: php-fpm
      container_name: fuzzy-telegram-php-fpm
      working_dir: /application
      volumes:
        - ..:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

